# Generated by Django 5.1.3 on 2025-03-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_movie", "0002_movie_budget_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
