# Generated by Django 5.1.3 on 2025-03-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_movie", "0003_movie_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EU", "Euro"),
                    ("DO", "Dollar"),
                    ("RU", "Rubles"),
                    ("SR", "Senior"),
                    ("GR", "Graduate"),
                ],
                default="RU",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
