# Generated by Django 5.1.3 on 2025-03-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_movie", "0004_movie_currency_alter_movie_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "Euro"),
                    ("USD", "Dollar"),
                    ("RUB", "Rubles"),
                    ("SR", "Senior"),
                    ("GR", "Graduate"),
                ],
                default="RU",
                max_length=3,
            ),
        ),
    ]
