# Generated by Django 5.1.3 on 2025-03-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_movie", "0007_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app_movie.director"
            ),
        ),
    ]
