# Generated by Django 5.1.3 on 2025-03-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_movie", "0012_alter_movie_director"),
    ]

    operations = [
        migrations.RenameField(
            model_name="director",
            old_name="last_first",
            new_name="name_last",
        ),
        migrations.AlterField(
            model_name="movie",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("USD", "Dollar"), ("RUB", "Rubles")],
                default="RUB",
                max_length=3,
            ),
        ),
    ]
