# Generated by Django 5.1.3 on 2025-03-23 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_movie", "0013_rename_last_first_director_name_last_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_first", models.CharField(default="режиссер", max_length=100)),
                ("name_last", models.CharField(default="1", max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужчина"), ("F", "Женщина")],
                        default="M",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="director",
            name="name_first",
            field=models.CharField(default="режиссер", max_length=100),
        ),
        migrations.AlterField(
            model_name="director",
            name="name_last",
            field=models.CharField(default="1", max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_movie.director",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(to="app_movie.actor"),
        ),
    ]
