# Generated by Django 5.1.3 on 2025-03-23 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_movie", "0014_actor_alter_director_name_first_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomDressing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.IntegerField()),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="actor",
            name="name_first",
            field=models.CharField(default="актер_имя", max_length=100),
        ),
        migrations.AlterField(
            model_name="actor",
            name="name_last",
            field=models.CharField(default="актер_фамилия", max_length=100),
        ),
        migrations.AlterField(
            model_name="director",
            name="name_first",
            field=models.CharField(default="режиссер_имя", max_length=100),
        ),
        migrations.AlterField(
            model_name="director",
            name="name_last",
            field=models.CharField(default="режиссер_фамилия", max_length=100),
        ),
        migrations.AddField(
            model_name="actor",
            name="roomDressing",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_movie.roomdressing",
            ),
        ),
    ]
