# Generated by Django 5.1.3 on 2025-03-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_movie", "0009_alter_movie_director"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="director",
            new_name="director2",
        ),
    ]
