# Generated by Django 5.1.3 on 2025-03-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="budget",
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
