# Generated by Django 5.1.3 on 2025-03-21 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_movie", "0005_alter_movie_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(default="режиссер-1", max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="budget",
            field=models.IntegerField(
                default=1000000,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "Euro"),
                    ("USD", "Dollar"),
                    ("RUB", "Rubles"),
                    ("SR", "Senior"),
                    ("GR", "Graduate"),
                ],
                default="RUB",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(default="", null=True),
        ),
    ]
