# Generated by Django 5.1.3 on 2025-03-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_movie", "0006_movie_director_alter_movie_budget_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_first", models.CharField(default="режиссер-1", max_length=100)),
                ("last_first", models.CharField(default="режиссер-1", max_length=100)),
                ("director_email", models.EmailField(max_length=254)),
            ],
        ),
    ]
